services:
  db:
    image: postgres:16-alpine
    container_name: odoo-backend-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: odoohackathon
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d odoohackathon"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: odoo-backend-app
    restart: always
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - NODE_ENV=development
      - JWT_SECRET=HiikGdnyJ7RlG6XPfZShgIlMuW7RWSYKjZIc41YZVQA
      - DATABASE_URL=postgresql://postgres:postgrespassword@db:5432/odoohackathon?schema=public
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  pgdata:
