import React, { useEffect } from 'react';
import { X, ExternalLink, Calendar, ShieldCheck, CheckCircle2, Clock } from 'lucide-react';
import NotificationTypeBadge from './NotificationTypeBadge';
import NotificationStatusBadge from './NotificationStatusBadge';

export default function NotificationDetailsModal({
  isOpen,
  onClose,
  notification,
  onMarkRead,
}) {
  // Prevent background scroll when open
  useEffect(() => {
    if (isOpen) {
      document.body.style.overflow = 'hidden';
    } else {
      document.body.style.overflow = 'unset';
    }
    return () => {
      document.body.style.overflow = 'unset';
    };
  }, [isOpen]);

  if (!isOpen || !notification) return null;

  const { id, title, description, type, status, createdAt, module, relatedEntity, timeline = [] } = notification;
  const isUnread = status === 'Unread';

  const handleMarkAsRead = () => {
    onMarkRead(id);
  };

  const handleGoToEntity = () => {
    if (relatedEntity) {
      alert(`Navigating to ${relatedEntity.type} detail: ${relatedEntity.name} (${relatedEntity.id})`);
    } else {
      alert(`Navigating to ${module} module page...`);
    }
    onClose();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 sm:p-6 select-none">
      {/* Backdrop overlay */}
      <div
        className="fixed inset-0 bg-[#0F172A]/40 backdrop-blur-[2px] transition-opacity duration-300"
        onClick={onClose}
      />

      {/* Modal Box (width 700px) */}
      <div className="bg-white rounded-2xl shadow-2xl border border-[#E5E7EB] w-full max-w-[700px] max-h-[90vh] flex flex-col relative z-10 overflow-hidden transform transition-all scale-100 duration-300 animate-in fade-in zoom-in-95">
        
        {/* Header */}
        <div className="flex items-start justify-between border-b border-[#E5E7EB] px-6 py-4.5 bg-gray-50/50">
          <div className="flex flex-col gap-0.5 text-left">
            <h2 className="text-base font-black text-[#111827]">Notification Details</h2>
            <p className="text-xs font-semibold text-[#6B7280]">
              Review the full notification information.
            </p>
          </div>
          <button
            type="button"
            onClick={onClose}
            className="p-1.5 hover:bg-gray-100 text-[#9CA3AF] hover:text-[#475569] rounded-xl transition-colors cursor-pointer"
            title="Close Modal"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Scrollable Modal Content */}
        <div className="flex-grow overflow-y-auto p-6 scrollbar-thin text-left flex flex-col gap-6">
          
          {/* Section 1: Main Header & Title */}
          <div className="flex flex-col gap-3">
            <div className="flex items-center gap-3">
              <NotificationTypeBadge type={type} />
              <NotificationStatusBadge status={status} />
            </div>
            <h3 className="text-lg font-black text-[#111827] leading-snug">{title}</h3>
            <p className="text-xs font-semibold text-[#475569] leading-relaxed bg-gray-50 border border-gray-100 rounded-xl p-4">
              {description}
            </p>
          </div>

          <div className="border-t border-[#F3F4F6] w-full" />

          {/* Section 2: Metadata Grid */}
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            {/* Generated By */}
            <div className="flex flex-col gap-1">
              <span className="text-[10px] font-bold text-[#9CA3AF] uppercase tracking-wider">
                Generated By
              </span>
              <span className="text-xs font-bold text-[#111827] bg-[#F8FAFC] border border-[#E2E8F0] px-3 py-2 rounded-xl inline-block w-fit">
                {module || 'System'}
              </span>
            </div>

            {/* Created At */}
            <div className="flex flex-col gap-1">
              <span className="text-[10px] font-bold text-[#9CA3AF] uppercase tracking-wider">
                Timestamp
              </span>
              <div className="flex items-center gap-2 text-xs font-semibold text-[#475569] bg-[#F8FAFC] border border-[#E2E8F0] px-3 py-2 rounded-xl w-fit">
                <Clock className="w-4 h-4 text-[#7C3AED]" />
                <span>
                  {new Date(createdAt).toLocaleDateString('en-GB', {
                    day: 'numeric',
                    month: 'long',
                    year: 'numeric',
                  })}
                  {' at '}
                  {new Date(createdAt).toLocaleTimeString('en-US', {
                    hour: '2-digit',
                    minute: '2-digit',
                    hour12: true,
                  })}
                </span>
              </div>
            </div>

            {/* Related Entity */}
            {relatedEntity && (
              <div className="flex flex-col gap-1 sm:col-span-2">
                <span className="text-[10px] font-bold text-[#9CA3AF] uppercase tracking-wider">
                  Related Entity
                </span>
                <button
                  onClick={handleGoToEntity}
                  className="flex items-center gap-2 text-xs font-bold text-[#7C3AED] hover:text-[#6D28D9] bg-[#F5F3FF] border border-[#EDE9FE] hover:bg-[#EDE9FE] px-3.5 py-2.5 rounded-xl w-fit transition-colors cursor-pointer"
                >
                  <span>{relatedEntity.type}: {relatedEntity.name} ({relatedEntity.id})</span>
                  <ExternalLink className="w-3.5 h-3.5" />
                </button>
              </div>
            )}
          </div>

          <div className="border-t border-[#F3F4F6] w-full" />

          {/* Section 3: Timeline */}
          <div className="flex flex-col gap-4">
            <span className="text-[10px] font-bold text-[#9CA3AF] uppercase tracking-wider">
              Notification Status Timeline
            </span>

            {/* Vertical timeline tree */}
            <div className="relative pl-6 flex flex-col gap-6">
              {/* Vertical connecting line */}
              <div className="absolute top-1 left-2.5 bottom-1 w-0.5 bg-[#E5E7EB]" />

              {timeline.map((event, idx) => (
                <div key={idx} className="relative flex items-start gap-4">
                  {/* Timeline icon indicator */}
                  <div className="absolute -left-6.5 mt-0.5 w-5.5 h-5.5 rounded-full bg-white border-2 border-[#7C3AED] flex items-center justify-center z-10">
                    <div className="w-1.5 h-1.5 rounded-full bg-[#7C3AED]" />
                  </div>

                  {/* Event labels */}
                  <div className="flex flex-col text-left">
                    <span className="text-xs font-black text-[#111827]">{event.title}</span>
                    <span className="text-[10px] font-semibold text-[#6B7280]">{event.time}</span>
                  </div>
                </div>
              ))}
            </div>
          </div>

        </div>

        {/* Footer Actions */}
        <div className="border-t border-[#E5E7EB] px-6 py-4.5 bg-gray-50/50 flex items-center justify-between gap-4">
          <button
            type="button"
            onClick={onClose}
            className="h-11 px-5 border border-[#E5E7EB] hover:bg-gray-100 text-[#475569] font-bold text-xs rounded-xl transition-colors cursor-pointer text-center"
          >
            Close
          </button>

          <div className="flex items-center gap-3">
            {isUnread && (
              <button
                type="button"
                onClick={handleMarkAsRead}
                className="h-11 px-5 border border-[#7C3AED] hover:bg-[#F5F3FF] text-[#7C3AED] font-bold text-xs rounded-xl transition-colors cursor-pointer"
              >
                Mark as Read
              </button>
            )}

            <button
              type="button"
              onClick={handleGoToEntity}
              className="h-11 px-6 bg-[#7C3AED] hover:bg-[#6D28D9] text-white font-bold text-xs rounded-xl flex items-center justify-center gap-1.5 transition-all cursor-pointer hover:scale-105 active:scale-95 shadow-md shadow-[#7C3AED]/15"
            >
              <span>Go to Related Page</span>
              <ExternalLink className="w-4 h-4" />
            </button>
          </div>
        </div>

      </div>
    </div>
  );
}
